#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Aug 17 11:21:09 BST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -prj DuneNvmeTestTop_vlog.prj"
xvlog --incr --relax -prj DuneNvmeTestTop_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj DuneNvmeTestTop_vhdl.prj"
xvhdl --incr --relax -prj DuneNvmeTestTop_vhdl.prj 2>&1 | tee -a compile.log

