#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Aug 17 11:21:38 BST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto c3d74f0fe10846d7a366cb9e6cde038a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot DuneNvmeTestTop_func_synth xil_defaultlib.DuneNvmeTestTop xil_defaultlib.glbl -log elaborate.log"
xelab -wto c3d74f0fe10846d7a366cb9e6cde038a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot DuneNvmeTestTop_func_synth xil_defaultlib.DuneNvmeTestTop xil_defaultlib.glbl -log elaborate.log

