# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xcku115-flva1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.cache/wt [current_project]
set_property parent.project_path /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeStoragePkg.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeStorageIntPkg.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/AxisClockConverter.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/AxisDataConvertFifo.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/Cdc.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/Fifo.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeConfig.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeQueues.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeRead.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeSim.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeStorage.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeStorageUnit.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeStreamMux.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/NvmeStrmFmtTestData.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/NvmeWrite.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/PcieStreamMux.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/Ram.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/RegAccessClockConvertor.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/StreamSwitch.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_strm_fmt_pkg.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/axis_stream_check_blk.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/axis_stream_flow_mod_blk.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_axis_packet_fifo.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_header_inserter_blk.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_pad_inserter_blk.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_spkt_splitter_blk.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_strm_fmt.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/BlockFormatting/nvme_strm_gen_blk.vhd
  /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/DuneNvmeTestTop.vhd
}
read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Axis_clock_converter/Axis_clock_converter.xci
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Axis_clock_converter/Axis_clock_converter_ooc.xdc]

read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/Pcie_nvme1.xci
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/synth/Pcie_nvme1_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/synth/Pcie_nvme1_gt.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/source/Pcie_nvme1-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/synth/Pcie_nvme1_ooc.xdc]

read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16.xci
set_property is_enabled false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16.xdc]

read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/Pcie_nvme0.xci
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/ip_0/synth/Pcie_nvme0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/ip_0/synth/Pcie_nvme0_gt.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/source/Pcie_nvme0-PCIE_X0Y2.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/synth/Pcie_nvme0_ooc.xdc]

read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_data_fifo_ic_512_x_256/axis_data_fifo_ic_512_x_256.xci
set_property is_enabled false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_data_fifo_ic_512_x_256/axis_data_fifo_ic_512_x_256_ooc.xdc]

read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Clk_core/Clk_core.xci
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Clk_core/Clk_core_board.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Clk_core/Clk_core.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Clk_core/Clk_core_ooc.xdc]

read_ip -quiet /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/Pcie_host.xci
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/synth/Pcie_host_pcie3_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/synth/Pcie_host_pcie3_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/source/Pcie_host_pcie3_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/synth/Pcie_host_pcie3_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/Pcie_host_board.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/source/Pcie_host_pcie3_us_ip.xdc]
set_property used_in_implementation false [get_files -all /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/synth/Pcie_host_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/DuneNvmeTestTop.xdc
set_property used_in_implementation false [get_files /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/src/DuneNvmeTestTop.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top DuneNvmeTestTop -part xcku115-flva1517-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DuneNvmeTestTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DuneNvmeTestTop_utilization_synth.rpt -pb DuneNvmeTestTop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
