# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/Pcie_nvme1.xci
# IP: The module: 'Pcie_nvme1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/Pcie_nvme1_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pcie_nvme1_gt || ORIG_REF_NAME==Pcie_nvme1_gt} -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/synth/Pcie_nvme1_gt_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/synth/Pcie_nvme1_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pcie_nvme1_gt || ORIG_REF_NAME==Pcie_nvme1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/source/Pcie_nvme1-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_nvme1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/synth/Pcie_nvme1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_nvme1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/Pcie_nvme1.xci
# IP: The module: 'Pcie_nvme1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/Pcie_nvme1_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pcie_nvme1_gt || ORIG_REF_NAME==Pcie_nvme1_gt} -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/synth/Pcie_nvme1_gt_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/ip_0/synth/Pcie_nvme1_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pcie_nvme1_gt || ORIG_REF_NAME==Pcie_nvme1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/source/Pcie_nvme1-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_nvme1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme1/synth/Pcie_nvme1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_nvme1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
