set_property SRC_FILE_INFO {cfile:/usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/synth/Pcie_nvme0_ooc.xdc rfile:../../../DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/synth/Pcie_nvme0_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:/usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/source/Pcie_nvme0-PCIE_X0Y2.xdc rfile:../../../DuneNvmeTest.srcs/sources_1/ip/Pcie_nvme0/source/Pcie_nvme0-PCIE_X0Y2.xdc id:2 order:EARLY scoped_inst:U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 1 [get_nets {U0/gt_top_i/PHY_TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_nets {U0/gt_top_i/PHY_TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 1 [get_nets {U0/gt_top_i/PHY_TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 1 [get_pins {U0/gt_top_i/bufg_mcap_clk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/bufg_mcap_clk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/bufg_mcap_clk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_case_analysis 0 [get_pins {U0/gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[2]}]
current_instance U0
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_3_1_X0Y2 [get_cells pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/PCIE_3_1_inst]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X16Y57 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_rep_inst/bram_rep_8k_inst/RAMB36E2[0].ramb36e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X16Y58 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_rep_inst/bram_rep_8k_inst/RAMB36E2[1].ramb36e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y98 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[0].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y99 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[1].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y100 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[2].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y101 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[3].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y104 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[0].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y105 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[1].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y106 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[2].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y107 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[3].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y108 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[4].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y109 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[5].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y110 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[6].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y111 [get_cells {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[7].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_nets {gt_top_i/PHY_TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_nets {gt_top_i/PHY_TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_nets {gt_top_i/PHY_TXOUTCLKSEL[0]}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins [list {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]}]]
set_property src_info {type:SCOPED_XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins [list {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]}]]
set_property src_info {type:SCOPED_XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins [list {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]}]]
set_property src_info {type:SCOPED_XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins [list {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {U0/gt_top_i/gt_wizard.gtwizard_top_i/Pcie_nvme0_gt_i/inst/gen_gtwizard_gthe3_top.Pcie_nvme0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[27].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]}]]
current_instance U0
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {gt_top_i/bufg_mcap_clk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/bufg_mcap_clk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/bufg_mcap_clk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold  1 -start -through [get_pins [get_pins {pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/PCIE_3_1_inst/CFGLTSSMSTATE pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/PCIE_3_1_inst/CFGNEGOTIATEDWIDTH}] -filter DIRECTION==OUT]
set_property src_info {type:SCOPED_XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-1}  -internal  -tags "1019576" -desc "properly_synced" -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter { NAME =~ *pipe_misc_inst/pipe_stages_1.pipe_tx_rate_q_reg[*]}]] -to [get_pins -filter {REF_PIN_NAME=~D} -of_objects [get_cells -hierarchical -filter { NAME =~ *rxlpmen_i_reg[*]}]]
