# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16.xci
# IP: The module: 'axis_fifo_cc_512_x_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_cc_512_x_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16.xci
# IP: The module: 'axis_fifo_cc_512_x_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/axis_fifo_cc_512_x_16/axis_fifo_cc_512_x_16.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_cc_512_x_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
