# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Axis_clock_converter/Axis_clock_converter.xci
# IP: The module: 'Axis_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Axis_clock_converter/Axis_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Axis_clock_converter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Axis_clock_converter/Axis_clock_converter.xci
# IP: The module: 'Axis_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Axis_clock_converter/Axis_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Axis_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
