# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/Pcie_host.xci
# IP: The module: 'Pcie_host' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/Pcie_host_pcie3_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip || ORIG_REF_NAME==Pcie_host_pcie3_ip} -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/Pcie_host_pcie3_ip_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip_gt || ORIG_REF_NAME==Pcie_host_pcie3_ip_gt} -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_1/xdma_v4_1_4_blk_mem_64_reg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be} -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/synth/Pcie_host_pcie3_ip_gt_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/synth/Pcie_host_pcie3_ip_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip_gt || ORIG_REF_NAME==Pcie_host_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/source/Pcie_host_pcie3_ip-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip || ORIG_REF_NAME==Pcie_host_pcie3_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/synth/Pcie_host_pcie3_ip_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/Pcie_host_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_host'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/source/Pcie_host_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_host'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/synth/Pcie_host_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_host'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/Pcie_host.xci
# IP: The module: 'Pcie_host' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/Pcie_host_pcie3_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip || ORIG_REF_NAME==Pcie_host_pcie3_ip} -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/Pcie_host_pcie3_ip_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip_gt || ORIG_REF_NAME==Pcie_host_pcie3_ip_gt} -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_1/xdma_v4_1_4_blk_mem_64_reg_be.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_reg_be} -quiet] -quiet

# IP: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_4_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/synth/Pcie_host_pcie3_ip_gt_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/ip_0/synth/Pcie_host_pcie3_ip_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip_gt || ORIG_REF_NAME==Pcie_host_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/source/Pcie_host_pcie3_ip-PCIE_X0Y0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pcie_host_pcie3_ip || ORIG_REF_NAME==Pcie_host_pcie3_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_0/synth/Pcie_host_pcie3_ip_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/Pcie_host_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_host'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/source/Pcie_host_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_host'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /usersc/ag17009/NVMe/BlockFormatting/Test/pl-nvme/vivado/DuneNvmeTest.srcs/sources_1/ip/Pcie_host/synth/Pcie_host_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pcie_host'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
